const mongoose = require("mongoose");

let connectionPromise = null;

const connectDB = async () => {
    if (process.env.USE_MOCK_DB === "true") return;
    if (mongoose.connection.readyState === 1) return;
    if (connectionPromise) return connectionPromise;

    const uri = process.env.MONGODB_URI;
    const isPlaceholder = !uri || uri.includes("<user_name>") || uri.includes("<password>") || uri.includes("7udof89w.mongodb.net");

    // Add safe fallback for JWT_SECRET if missing or using standard placeholder
    if (!process.env.JWT_SECRET || process.env.JWT_SECRET.includes("openssl rand")) {
        if (process.env.NODE_ENV === 'production') {
            console.error("\n❌ FATAL SECURITY ERROR: JWT_SECRET is not configured in production!");
            console.error("❌ Do not deploy without setting a strong JWT_SECRET environment variable.");
            process.exit(1);
        } else {
            const crypto = require('crypto');
            const fs = require('fs');
            const path = require('path');
            
            const newSecret = crypto.randomBytes(32).toString('hex');
            process.env.JWT_SECRET = newSecret;
            
            const envPath = path.join(process.cwd(), '.env.local');
            try {
                fs.appendFileSync(envPath, `\n# Auto-generated by CreatorOS for local development\nJWT_SECRET=${newSecret}\n`);
                console.warn("\n✅ JWT_SECRET was missing. A secure random secret was automatically generated and saved to your .env.local file.\n");
            } catch (err) {
                console.warn("\n⚠️  JWT_SECRET missing. Auto-generated a temporary random secret, but failed to save to .env.local.\n");
            }
        }
    }

    if (isPlaceholder) {
        if (process.env.NODE_ENV === 'production') {
            console.error("\n❌ FATAL ERROR: MongoDB URI is missing or invalid in production.");
            console.error("❌ Do not deploy without a valid MONGODB_URI environment variable.");
            process.exit(1);
        }
        console.log("\n==================================================");
        console.log("⚠️  MongoDB URI not configured or using placeholder.");
        console.log("👉 CreatorOS is starting in MOCK DATABASE mode.");
        console.log("👉 Test user credentials: test@local.com / Password123!");
        console.log("==================================================\n");
        process.env.USE_MOCK_DB = "true";
        return;
    }

    try {
        connectionPromise = mongoose.connect(uri, {
            serverSelectionTimeoutMS: 5000 // Slightly longer timeout for production
        });
        await connectionPromise;

        console.log("MongoDB Connected Successfully");
    } catch (error) {
        connectionPromise = null;
        if (process.env.NODE_ENV === 'production') {
            console.error("\n❌ FATAL ERROR: MongoDB Connection Failed in Production.");
            console.error("Error specifics:", error.message);
            console.error("👉 Ensure your MONGODB_URI is correct and the deployment server's IP is whitelisted in your MongoDB cluster (e.g., MongoDB Atlas Network Access).");
            process.exit(1);
        }
        console.log("\n==================================================");
        console.log("MongoDB Connection Error:", error.message);
        console.log("👉 CreatorOS is falling back to MOCK DATABASE mode.");
        console.log("👉 Test user credentials: test@local.com / Password123!");
        console.log("==================================================\n");
        process.env.USE_MOCK_DB = "true";
    }
};

module.exports = connectDB;
