module.exports = [
    {
        key: 'url-shortener',
        name: 'Titli 🦋 - URL Shortener',
        description: 'Create compact short links and redirect users reliably.',
        route: '/services/url-shortener',
        status: 'available',
    },
    {
        key: 'file-upload',
        name: '📁 File Upload',
        description: 'Drag and drop or click to upload files. Supports all common formats.',
        route: '/services/file-upload',
        status: 'available',
    },
    {
        key: 'smart-bio',
        name: '🔗 Smart Bio System',
        description: 'A smart mobile-first bio platform with branding, analytics, and custom domains.',
        route: '/services/smart-bio',
        status: 'coming_soon',
    },
    {
        key: 'analytics-dashboard',
        name: '📊 Analytics Dashboard',
        description: 'Track performance and engagement across your creator services.',
        route: '/services/analytics-dashboard',
        status: 'coming_soon',
    },
    {
        key: 'dm-automation',
        name: '🤖 DM Automation',
        description: 'Automate replies and deliver lead magnets via keyword triggers.',
        route: '/services/dm-automation',
        status: 'coming_soon',
    },
    {
        key: 'creator-crm',
        name: '🤝 Creator CRM',
        description: 'Manage brand deals, contacts, and campaign status in one place.',
        route: '/services/creator-crm',
        status: 'coming_soon',
    },
    {
        key: 'content-os',
        name: '🧠 Content OS',
        description: 'Organize ideas, scripts, and content planning workflows.',
        route: '/services/content-os',
        status: 'coming_soon',
    },
];
